XCODE_WORKSPACE='BothApps.xcworkspace'
XCODE_DESTINATION='fastlane/_build_app2'
XCODE_SCHEME='App2'
APP_IDENTIFIER='com.test.App2'
APP_SCREENSHOTS='screenshots_app2'
APP_METADATA='fastlane/metadata_app2'
APP_VERSION='1.0.7'
APPLE_ID='appleid@test.com'

echo "XCODE_WORKSPACE: $XCODE_WORKSPACE"
echo "XCODE_DESTINATION: $XCODE_DESTINATION"
echo "XCODE_SCHEME: $XCODE_SCHEME"
echo "APP_IDENTIFIER: $APP_IDENTIFIER"
echo "APP_SCREENSHOTS: $APP_SCREENSHOTS"
echo "APP_VERSION: $APP_VERSION"
echo "APP_METADATA: $APP_METADATA"
echo "APPLE_ID: $APPLE_ID"

fastlane deploy